# Generated by Django 6.0.2 on 2026-03-17 01:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    # This migration is intentionally left empty.
    # The final definitions of Product.price and Product.stock are already
    # represented in the initial migration for the store app. Keeping this
    # as a no-op avoids redundant migration churn for a brand-new app.
    operations = []
