# Generated by Django 6.0.2 on 2026-03-24 00:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('paid', 'Paid'),
                    ('confirmed', 'Confirmed'),
                    ('shipped', 'Shipped'),
                    ('delivered', 'Delivered'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending',
                max_length=20,
                verbose_name='status',
            ),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'payment_method',
                    models.CharField(
                        choices=[('stripe', 'Stripe')],
                        default='stripe',
                        max_length=20,
                        verbose_name='payment method',
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal('0.01')
                            )
                        ],
                        verbose_name='amount',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('succeeded', 'Succeeded'),
                            ('failed', 'Failed'),
                        ],
                        max_length=20,
                        verbose_name='status',
                    ),
                ),
                (
                    'transaction_id',
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name='transaction ID',
                    ),
                ),
                (
                    'paid_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='paid at',
                    ),
                ),
                (
                    'order',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payment',
                        to='orders.order',
                        verbose_name='order',
                    ),
                ),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
